/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:26: UserWarning: Converting G to a CSC matrix; may take a while.
  warn("Converting G to a CSC matrix; may take a while.")
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:29: UserWarning: Converting A to a CSC matrix; may take a while.
  warn("Converting A to a CSC matrix; may take a while.")
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/pettingzoo/atari/combat_tank_v1.py:8: UserWarning: combat_tank has interesting parameters to consider overriding including is_invisible, billiard_hit and has_maze
  warnings.warn("combat_tank has interesting parameters to consider overriding including is_invisible, billiard_hit and has_maze")
pygame 2.0.1 (SDL 2.0.14, Python 3.7.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
combat_tank_v1 pettingzoo
Load combat_tank_v1 environment in type pettingzoo.
Env observation space: Box(0.0, 1.0, (128,), float32) action space: Discrete(18)
random seed: 23
<mars.env.wrappers.mars_wrappers.Dict2TupleWrapper object at 0x7f888988c5c0>
Traceback (most recent call last):
  File "general_exploit.py", line 49, in <module>
    launch_rollout(parser_args.env, parser_args.method, parser_args.load_id, parser_args.save_id)
  File "general_exploit.py", line 31, in launch_rollout
    trained_model = eval(args.algorithm)(env, args)
  File "/home/zihan/research/MARS/mars/rl/agents/nash_dqn.py", line 21, in __init__
    super().__init__(env, args)
  File "/home/zihan/research/MARS/mars/rl/agents/dqn.py", line 19, in __init__
    self.model = self._select_type(env, args).to(self.device)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
